#  __  __ _            _____                           
# |  \/  (_)          |  __ \                          
# | \  / |_ _ __   ___| |__) | __ ___  _ __ ___   ___  
# | |\/| | | '_ \ / _ \  ___/ '__/ _ \| '_ ` _ \ / _ \ 
# | |  | | | | | |  __/ |   | | | (_) | | | | | | (_) |
# |_|  |_|_|_| |_|\___|_|   |_|  \___/|_| |_| |_|\___/  
#
# W A R N I N G: Use the ‘§’ symbol to specify a colour or 
# colour symbol. For example: ‘§6’. This example outputs the 
# colour gold. Or ‘§l’. The text will be bold.
#
#  ===========- INFO -=============
#  * File:         | config.yml
#  * Project:      | MinePromo
#  * Author:       | dmitriykotik
#  * Main file:    | MinePromo.java
#  ================================

properties:
  prefix: '§6§l[MinePromo]§r'

  # This point is needed to create a mask for the issued promo code. Use the X symbol to indicate the alphanumeric character being generated.
  mask: 'XXXXX-XXXXX-XXXXX'

messages:
  reload_start: '§c§o[Rebooting the configuration...]'
  reload_done: '§a§o[Configuration loaded!]'

  command_not_found: '§cДанная команда не обнаружена!'
  access_denied: '§cУ вас нет прав для выполнения этой команды.'

  created_promo: '§aПромокод создан:'
  deleted_promo: '§aПромокод был удалён!'
  promo_not_found: '§cНе удалось найти указанный промокод!'
  edited_promo: '§aПромокод был изменён!'
  invalid_promo: '§cНеверный промокод!'
  promo_expired: '§cСрок действия промокода истёк!'
  no_uses_left: '§cКол-во использований промокода превышено!'
  promo_applied: '§aПромокод применён!'
  
  help_create: 'Создаёт промокод'
  help_edit: 'Изменяет промокод'
  help_delete: 'Удаляет промокод'
  help_reload: 'Перезагружает плагин'
  help_promo: 'Активирует промокод'
